apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: kserve-test
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: thescorpoi/model-prometheus:v2
        ports:
        - containerPort: 4433

---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: kserve-test
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 4433
      targetPort: 4433

