apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: kubeflow-user-example-com
type: Opaque
data:
  MLFLOW_TRACKING_USERNAME: dXNlcg==
  MLFLOW_TRACKING_PASSWORD: dXhuc1lrelZhVQ==
