apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kserve-test
  name: kserve-role
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserve-rolebinding
  namespace: kserve-test
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: kubeflow-user-example-com
roleRef:
  kind: Role
  name: kserve-role
  apiGroup: rbac.authorization.k8s.io
